name: Deploy Static HTML to Apache

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 Apache
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy new HTML files
        run: |
          sudo cp -r * /var/www/html/
          sudo chown -R www-data:www-data /var/www/html/

      - name: Restart Apache
        run: |
          sudo systemctl restart apache2